# Generated by Django 5.2.5 on 2025-09-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
